### ISSUE TITLE
Using a Different Data Provider than IB

### ISSUE THREAD

**Issue by danielepiu** [letianzj/quanttrader#13]
Hi, I find this repository very interesting. I wanted to ask if it would be possible to use a different API as a data feed instead of IB, and how complex this modification might be to implement. Thank you

**Comment by letianzj** [comment]
Hi, it needs to add the data source in the brokerage folder similar to brokerage/ib_brokerage.py, specifically putting the live data into its self.tick_event_engine, then it will be automatically picked up by the trading system.

**Comment by letianzj** [comment]
answered
