### ISSUE TITLE
Delay order execution

### ISSUE THREAD

**Issue by wenq1** [letianzj/quanttrader#3]
Hi there,

Is there any way to delay order execution so as to match the design of backtrader? I know the immediate execution mode is by design, just want to have some flexibility.

I noted line below in strategy_base.py
```
        def adjust_position(self, sym, size_from, size_to, timestamp=None):
                """
                use market order to adjust position
                :param sym:
                :param size_from:
                :param size_to:
                :param timestamp: used by backtest broker to get price on timestamp
                :return:
                """
                if size_from == size_to:
                        return
                o = OrderEvent()
                o.full_symbol = sym
                o.order_type = OrderType.MARKET
                o.order_size = size_to - size_from
                o.source = self.id  # identify source
                if timestamp is None:
                        o.create_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')
                else:
                        o.create_time = timestamp

```

Is the `timestamp` arg intended for this?

**Comment by letianzj** [comment]
Hi, what do you mean by saying delayed execution? is it conditional order e.g. stop limit, or simply execute say 5sec after the order is sent?

**Comment by wenq1** [comment]
My definition of delayed execution is to match that of backtrader. "delayed execution" might not be the right word for it.
In backtrader, you can set_coc (True) so that the order execution price matches the creation price. However it is considered cheating. I'm modifying qt so that it can use the next market open price as the execution price.

I found a way to do it already, and will create a pull request if you want. In the mean time, checkout #4 for a minor fix encountered when working on this feature.
