### ISSUE TITLE
Ability to use ASK and BID candles

### ISSUE THREAD

**Issue by Sdoof** [letianzj/quanttrader#9]
IB provide bothe OHLC for ASDK and BID price, this is useful to include the spread as part of the trading cost and avoid specific time or stock where spread can be prohibitive. Hence more realistic simulation and backtesting. How would the source code needs to be modified to that end? Happy to help if I am provided some pointers

**Comment by letianzj** [comment]
Hi, the default fill is for the market orders to fill on the next tick. For limit orders, they will rest on the book until get filled. You can find the logic in `/brokerage/backtest_brokerage.py`. If you have level 2, the matching logic can be modified to sweep the book. As to the b/a spread, it is possible to check it before the order is sent, in on_tick function. In this case, the event is expected to be a tick event defined in `data/tick_event.py`.
